import Foundation

final class TherapistShareService: Sendable {
    static let shared = TherapistShareService()

    private init() {}

    // MARK: - Types

    struct EmotionSummary: Codable, Sendable {
        let emotion: String
        let percentage: Double
    }

    struct TherapeuticSummary: Codable, Sendable {
        let generatedAt: TimeInterval
        let entryCount: Int
        let startDate: TimeInterval
        let endDate: TimeInterval
        let dominantEmotions: [EmotionSummary]
        let sentimentTrend: TrendDirection
        let topTopics: [TopicSummary]
        let patternsFound: [String]
        let cognitiveDrift: String?
        let behavioralNotes: String
        let recommendation: String
        let disclaimer: String
    }

    struct TopicSummary: Codable, Sendable {
        let topic: String
        let overallSentiment: Double
        let mentionCount: Int
    }

    func generateSummary(entries: [JournalEntry], patterns: [DetectedPattern],
                         decisions: [JournalDecision]) -> TherapeuticSummary {
        let sorted = entries.sorted { $0.timestamp < $1.timestamp }
        let now = Date().timeIntervalSince1970

        // Emotion distribution
        var emotionCounts: [String: Int] = [:]
        for entry in entries {
            if let emotion = entry.emotion {
                emotionCounts[emotion.primaryEmotion.rawValue, default: 0] += 1
            }
        }
        let total = Double(max(emotionCounts.values.reduce(0, +), 1))
        let dominant = emotionCounts.sorted { $0.value > $1.value }
            .prefix(3)
            .map { EmotionSummary(emotion: $0.key, percentage: Double($0.value) / total) }

        // Sentiment trend
        let valences = sorted.compactMap { $0.emotion?.valence }
        let sentimentTrend: TrendDirection = valences.count >= 3
            ? (BiomarkerTrendService.computeSlope(valences) > 0 ? .increasing : .decreasing)
            : .stable

        // Top topics
        var topicAgg: [String: (sentiment: Double, count: Int)] = [:]
        for entry in sorted {
            guard let topics = entry.topics else { continue }
            for topic in topics {
                var existing = topicAgg[topic.topic] ?? (0, 0)
                existing.sentiment += topic.sentiment
                existing.count += 1
                topicAgg[topic.topic] = existing
            }
        }
        let topTopics = topicAgg.sorted { $0.value.count > $1.value.count }
            .prefix(5)
            .map { TopicSummary(topic: $0.key, overallSentiment: $0.value.sentiment / Double($0.value.count), mentionCount: $0.value.count) }

        // Pattern descriptions
        let patternDesc = patterns.filter { $0.severity >= 40 }.map { "\($0.title): \($0.message.prefix(100))" }

        // Cognitive drift summary
        let cognitiveDrift = try? CognitiveDriftService.shared.detectDrift(from: entries)

        // Behavioral notes
        var notes: [String] = []
        let streak = computeStreak(from: sorted)
        notes.append("Journaling consistency: \(streak)-day current streak with \(entries.count) total entries over \(daysBetween(sorted.first?.timestamp ?? now, sorted.last?.timestamp ?? now)) days.")

        let kept = decisions.filter { $0.status == .kept }.count
        let regretted = decisions.filter { $0.status == .regretted }.count
        if kept > 0 || regretted > 0 {
            notes.append("Decision tracking: \(kept) kept, \(regretted) regretted of \(decisions.count) decisions.")
        }

        if dominant.first?.emotion == "sadness" || dominant.first?.emotion == "anxiety" {
            notes.append("Predominant affect is \(dominant.first?.emotion ?? "neutral"). Recommend monitoring for persistent trends.")
        }

        return TherapeuticSummary(
            generatedAt: now,
            entryCount: entries.count,
            startDate: sorted.first?.timestamp ?? now,
            endDate: sorted.last?.timestamp ?? now,
            dominantEmotions: dominant,
            sentimentTrend: sentimentTrend,
            topTopics: topTopics,
            patternsFound: patternDesc,
            cognitiveDrift: cognitiveDrift.map { "\($0.overallSignificance.rawValue) — \($0.summary)" },
            behavioralNotes: notes.joined(separator: "\n"),
            recommendation: generateRecommendation(emotions: dominant, sentiment: sentimentTrend, patterns: patterns, decisions: decisions),
            disclaimer: "This summary is generated by Soulo AI and is not a clinical assessment. It is intended as a conversation aid for therapeutic use. Always consult a licensed healthcare provider for medical decisions."
        )
    }

    // MARK: - Export for Therapist

    func generateShareText(entries: [JournalEntry], patterns: [DetectedPattern],
                            decisions: [JournalDecision]) -> String {
        let summary = generateSummary(entries: entries, patterns: patterns, decisions: decisions)
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .medium

        var text = "Soulo — Therapeutic Summary\n"
        text += "Generated: \(dateFormatter.string(from: Date()))\n"
        text += "Entries: \(summary.entryCount) (\(dateFormatter.string(from: Date(timeIntervalSince1970: summary.startDate))) — \(dateFormatter.string(from: Date(timeIntervalSince1970: summary.endDate))))\n\n"

        text += "--- Dominant Emotions ---\n"
        for emotion in summary.dominantEmotions {
            text += "\(emotion.emotion.capitalized): \(Int(emotion.percentage * 100))%\n"
        }
        text += "\nSentiment Trend: \(summary.sentimentTrend.rawValue)\n\n"

        if !summary.topTopics.isEmpty {
            text += "--- Topics of Focus ---\n"
            for topic in summary.topTopics {
                text += "\(topic.topic): \(String(format: "%.1f", topic.overallSentiment)) sentiment (\(topic.mentionCount)×\n"
            }
            text += "\n"
        }

        if !summary.patternsFound.isEmpty {
            text += "--- Detected Patterns ---\n"
            for pattern in summary.patternsFound {
                text += "• \(pattern)\n"
            }
            text += "\n"
        }

        if let drift = summary.cognitiveDrift {
            text += "--- Cognitive Drift ---\n\(drift)\n\n"
        }

        text += "--- Behavioral Notes ---\n\(summary.behavioralNotes)\n\n"
        text += "--- Recommendation ---\n\(summary.recommendation)\n\n"
        text += "---\n\(summary.disclaimer)"

        return text
    }

    // MARK: - Private

    private func computeStreak(from entries: [JournalEntry]) -> Int {
        let cal = Calendar.current
        var streak = 0
        var day = cal.startOfDay(for: Date())
        let entryDays = Set(entries.map { cal.startOfDay(for: Date(timeIntervalSince1970: $0.timestamp)) })
        while entryDays.contains(day) { streak += 1; day = cal.date(byAdding: .day, value: -1, to: day)! }
        return streak
    }

    private func daysBetween(_ start: TimeInterval, _ end: TimeInterval) -> Int {
        max(1, Int((end - start) / 86400))
    }

    private func generateRecommendation(emotions: [(emotion: String, percentage: Double)],
                                         sentiment: TrendDirection,
                                         patterns: [DetectedPattern],
                                         decisions: [JournalDecision]) -> String {
        var recs: [String] = []

        if sentiment == .decreasing {
            recs.append("The declining sentiment trend warrants attention. Consider exploring contributing factors in therapy.")
        }

        let abandonmentPatterns = patterns.filter { $0.patternType == .goalAbandonment }
        if !abandonmentPatterns.isEmpty {
            recs.append("Patterns of goal abandonment detected (\(abandonmentPatterns.count) instances). Breaking goals into smaller steps may help.")
        }

        let regretCount = decisions.filter { $0.status == .regretted }.count
        if regretCount >= 2 {
            recs.append("Frequent decision regret (\(regretCount) instances) suggests evaluating decision-making patterns.")
        }

        if let top = emotions.first, top.emotion == "anxiety" || top.emotion == "fear" {
            recs.append("Anxiety/fear is the predominant emotion. Mindfulness and grounding techniques may be beneficial.")
        }

        if recs.isEmpty {
            recs.append("Continue monitoring. Consistent journaling provides the best data for pattern recognition.")
        }

        return recs.joined(separator: "\n")
    }
}
