package com.soulo.app.services

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import com.soulo.app.SouloApplication
import com.soulo.app.models.*
import java.io.File

object TherapistShareService {
    data class EmotionSummary(val emotion: String, val percentage: Double)
    data class TopicSummary(val topic: String, val overallSentiment: Double, val mentionCount: Int)

    data class TherapeuticSummary(
        val entryCount: Int,
        val startDate: Long,
        val endDate: Long,
        val dominantEmotions: List<EmotionSummary>,
        val sentimentTrend: TrendDirection,
        val topTopics: List<TopicSummary>,
        val patternsFound: List<String>,
        val cognitiveDrift: String?,
        val behavioralNotes: String,
        val recommendation: String,
        val disclaimer: String = "This summary is generated by Soulo AI and is not a clinical assessment. It is intended as a conversation aid for therapeutic use. Always consult a licensed healthcare provider for medical decisions."
    )

    fun generateSummary(
        entries: List<JournalEntry>,
        patterns: List<DetectedPattern>,
        decisions: List<JournalDecision>
    ): TherapeuticSummary {
        val sorted = entries.sortedBy { it.timestamp }
        val now = System.currentTimeMillis() / 1000

        // Emotion distribution
        val emotionCounts = mutableMapOf<String, Int>()
        for (entry in entries) {
            entry.emotion?.let { e ->
                emotionCounts[e.primaryEmotion.name] = (emotionCounts[e.primaryEmotion.name] ?: 0) + 1
            }
        }
        val total = maxOf(emotionCounts.values.sum().toDouble(), 1.0)
        val dominant = emotionCounts.entries
            .sortedByDescending { it.value }
            .take(3)
            .map { EmotionSummary(it.key, it.value / total) }

        // Sentiment trend
        val valences = sorted.mapNotNull { it.emotion?.valence }
        val sentimentTrend = when {
            valences.size < 3 -> TrendDirection.stable
            BiomarkerTrendService.computeSlope(valences) > 0 -> TrendDirection.increasing
            else -> TrendDirection.decreasing
        }

        // Top topics
        val topicMap = mutableMapOf<String, Pair<Double, Int>>()
        for (entry in sorted) {
            entry.topics?.forEach { t ->
                val existing = topicMap[t.topic] ?: (0.0 to 0)
                topicMap[t.topic] = (existing.first + t.sentiment) to (existing.second + 1)
            }
        }
        val topTopics = topicMap.map { (topic, data) ->
            TopicSummary(topic, data.first / maxOf(data.second, 1), data.second)
        }.sortedByDescending { it.mentionCount }.take(5)

        // Patterns
        val patternDesc = patterns.map { "${it.title}: ${it.message}" }

        // Cognitive drift
        val cognitiveDriftText = null // TODO: Integrate CognitiveDriftService

        // Behavioral notes
        val notes = mutableListOf<String>()
        val entryCount = entries.size
        val daysSpan = if (sorted.isNotEmpty()) {
            (sorted.last().timestamp - sorted.first().timestamp) / 86400
        } else 0
        notes.add("Journaling span: $daysSpan days with $entryCount entries.")
        if (decisions.isNotEmpty()) {
            val kept = decisions.count { it.status == DecisionStatus.kept }
            val regretted = decisions.count { it.status == DecisionStatus.regretted }
            notes.add("Decisions tracked: $kept kept, $regretted regretted of ${decisions.size}.")
        }

        // Recommendation
        val recommendation = generateRecommendation(dominant, sentimentTrend, patterns, decisions)

        return TherapeuticSummary(
            entryCount = entryCount,
            startDate = sorted.firstOrNull()?.timestamp ?: now,
            endDate = sorted.lastOrNull()?.timestamp ?: now,
            dominantEmotions = dominant,
            sentimentTrend = sentimentTrend,
            topTopics = topTopics,
            patternsFound = patternDesc,
            cognitiveDrift = cognitiveDriftText,
            behavioralNotes = notes.joinToString("\n"),
            recommendation = recommendation
        )
    }

    fun generateShareText(
        entries: List<JournalEntry>,
        patterns: List<DetectedPattern>,
        decisions: List<JournalDecision>
    ): String {
        val summary = generateSummary(entries, patterns, decisions)
        val dateFmt = java.text.SimpleDateFormat("MMM d, yyyy", java.util.Locale.US)

        return buildString {
            appendLine("Soulo \u2014 Therapeutic Summary")
            appendLine("Generated: ${dateFmt.format(java.util.Date())}")
            appendLine("Entries: ${summary.entryCount} " +
                "(${dateFmt.format(java.util.Date(summary.startDate * 1000))} \u2014 " +
                "${dateFmt.format(java.util.Date(summary.endDate * 1000))})")
            appendLine()

            appendLine("--- Dominant Emotions ---")
            summary.dominantEmotions.forEach { e ->
                appendLine("${e.emotion.capitalize()}: ${(e.percentage * 100).toInt()}%")
            }
            appendLine("Sentiment Trend: ${summary.sentimentTrend.name}")
            appendLine()

            if (summary.topTopics.isNotEmpty()) {
                appendLine("--- Topics of Focus ---")
                summary.topTopics.forEach { t ->
                    appendLine("${t.topic}: ${"%.1f".format(t.overallSentiment)} sentiment (${t.mentionCount}x)")
                }
                appendLine()
            }

            if (summary.patternsFound.isNotEmpty()) {
                appendLine("--- Detected Patterns ---")
                summary.patternsFound.forEach { appendLine("\u2022 $it") }
                appendLine()
            }

            summary.cognitiveDrift?.let {
                appendLine("--- Cognitive Drift ---")
                appendLine(it)
                appendLine()
            }

            appendLine("--- Behavioral Notes ---")
            appendLine(summary.behavioralNotes)
            appendLine()

            appendLine("--- Recommendation ---")
            appendLine(summary.recommendation)
            appendLine()

            appendLine("---")
            appendLine(summary.disclaimer)
        }
    }

    fun copyToClipboard(text: String) {
        val ctx = SouloApplication.instance
        val clipboard = ctx.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
        clipboard.setPrimaryClip(ClipData.newPlainText("Soulo Therapy Summary", text))
    }

    fun shareText(text: String) {
        val ctx = SouloApplication.instance
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
        }
        ctx.startActivity(Intent.createChooser(intent, "Share with Therapist"))
    }

    private fun generateRecommendation(
        emotions: List<EmotionSummary>,
        sentiment: TrendDirection,
        patterns: List<DetectedPattern>,
        decisions: List<JournalDecision>
    ): String {
        val parts = mutableListOf<String>()
        if (sentiment == TrendDirection.decreasing && patterns.any { it.type == PatternType.sentimentDecline }) {
            parts.add("Consider discussing recent sentiment decline with your therapist. There may be underlying patterns worth exploring.")
        }
        if (patterns.any { it.type == PatternType.goalCycle }) {
            parts.add("Goal cycle patterns detected. Breaking goals into smaller milestones may help build momentum.")
        }
        if (patterns.any { it.type == PatternType.relationshipPattern }) {
            parts.add("Relationship patterns were identified. These may benefit from guided exploration.")
        }
        if (emotions.any { it.emotion == "anxiety" || it.emotion == "sadness" }) {
            parts.add("Persistent ${emotions.first { e -> e.emotion == "anxiety" || e.emotion == "sadness" }.emotion} noted. Regular check-ins with your provider are recommended.")
        }
        return parts.joinToString("\n").ifEmpty {
            "Continue your journaling practice. Consistency provides the most valuable data for understanding your patterns."
        }
    }

    private fun String.capitalize(): String =
        replaceFirstChar { if (it.isLowerCase()) it.titlecase(java.util.Locale.US) else it.toString() }
}
